spring:
  application:
    name: suda-eda
  liquibase:
    enabled: true
    change-log: classpath:/db/migrations/changelogMaster.yaml
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/studs
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
springdoc:
  swagger-ui:
    path: '/swagger-ui'
logging:
  level:
    root: info
