spring:
  application:
    name: suda-eda
  liquibase:
    enabled: false

datasource:
  jdbc-url: jdbc:postgresql://localhost:5432/studs
  username: postgres
  password: postgres

analytics-datasource:
  jdbc-url: jdbc:postgresql://localhost:5432/analytics
  username: postgres
  password: postgres

springdoc:
  swagger-ui:
    path: '/swagger-ui'

logging:
  level:
    root: info

liquibase:
  primary:
    change-log: classpath:/db/migrations/primary/changelogMaster.yaml
  analytics:
    change-log: classpath:/db/migrations/analytics/changelogMaster.yaml
