spring:
  application:
    name: suda-eda
  liquibase:
    enabled: false
  artemis:
    broker-url: amqp://localhost:5672
    user: admin
    password: admin
    mode: native
  quartz:
    job-store-type: memory
    properties:
      org.quartz.threadPool.threadCount: 5
    wait-for-jobs-to-complete-on-shutdown: true

keycloak:
  server-url: http://localhost:8081
  realm: suda-eda
  client-id: suda-eda-client
  client-secret: ${KC_CLIENT_SECRET}
  grant-type: client_credentials

datasource:
  jdbc-url: jdbc:postgresql://localhost:5432/studs
  username: postgres
  password: postgres

analytics-datasource:
  jdbc-url: jdbc:postgresql://localhost:5432/analytics
  username: postgres
  password: postgres

springdoc:
  swagger-ui:
    path: '/swagger-ui'

logging:
  level:
    root: info

liquibase:
  primary:
    change-log: classpath:/db/migrations/primary/changelogMaster.yaml
  analytics:
    change-log: classpath:/db/migrations/analytics/changelogMaster.yaml

artemis:
  username: admin
  password: admin
  order-status-update-queue: order-status-update-queue
